const { app, BrowserWindow } = require('electron')
const path = require('path')
app.setAppUserModelId('com.soundflow.diag2')
app.whenReady().then(() => {
  console.log('[diag] ready')
  const win = new BrowserWindow({ width: 400, height: 300, show: true, webPreferences: { nodeIntegration: false, contextIsolation: true, webSecurity: false } })
  win.webContents.on('console-message', (e, level, message) => console.log('[page]', message))
  win.loadFile(path.join(__dirname, 'test-page2.html'))
  setTimeout(() => { console.log('[diag] 退出'); app.exit(0) }, 22000)
})
app.on('window-all-closed', () => app.exit(0))
